import { Component, inject } from '@angular/core'; import { ActivatedRoute, Router, RouterLink } from '@angular/router'; import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatInputModule } from '@angular/material/input'; import { MatCheckboxModule } from '@angular/material/checkbox'; import { MatButtonModule } from '@angular/material/button';
import { DriverService } from '../../../core/services/driver.service'; import { ApiErrorService } from '../../../core/services/api-error.service';
@Component({selector:'app-driver-form',standalone:true,imports:[ReactiveFormsModule,RouterLink,MatCardModule,MatFormFieldModule,MatInputModule,MatCheckboxModule,MatButtonModule],templateUrl:'./driver-form.component.html',styleUrl:'./driver-form.component.css'})
export class DriverFormComponent{
 private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly service=inject(DriverService);private readonly errors=inject(ApiErrorService);
 readonly form=this.fb.nonNullable.group({firstName:['',Validators.required],lastName:['',Validators.required],email:['',[Validators.required,Validators.email]],password:[''],phoneNumber:[''],licenseNumber:['',Validators.required],licenseExpiryDate:['',Validators.required],experienceYears:[0,[Validators.required,Validators.min(0)]],isAvailable:[true]});
 id:number|null=null;loading=false;error='';get editing():boolean{return this.id!==null;}
 ngOnInit():void{const raw=this.route.snapshot.paramMap.get('id');this.id=raw?Number(raw):null;if(this.id){this.form.controls.email.disable();this.form.controls.password.clearValidators();this.form.controls.password.updateValueAndValidity();this.service.getById(this.id).subscribe({next:d=>this.form.patchValue({firstName:d.firstName,lastName:d.lastName,email:d.email,phoneNumber:d.phoneNumber??'',licenseNumber:d.licenseNumber,licenseExpiryDate:d.licenseExpiryDate.slice(0,10),experienceYears:d.experienceYears,isAvailable:d.isAvailable}),error:e=>this.error=this.errors.message(e)});}else{this.form.controls.password.setValidators([Validators.required,Validators.minLength(8)]);this.form.controls.password.updateValueAndValidity();}}
 submit():void{if(this.form.invalid){this.form.markAllAsTouched();return;}this.loading=true;this.error='';const x=this.form.getRawValue();if(this.id){const req={firstName:x.firstName,lastName:x.lastName,phoneNumber:x.phoneNumber||null,licenseNumber:x.licenseNumber,licenseExpiryDate:x.licenseExpiryDate,experienceYears:x.experienceYears,isAvailable:x.isAvailable};this.service.update(this.id,req).subscribe({next:()=>{this.loading=false;void this.router.navigate(['/admin/drivers']);},error:e=>{this.loading=false;this.error=this.errors.message(e);}});}else{const req={...x,phoneNumber:x.phoneNumber||null,licenseExpiryDate:x.licenseExpiryDate};this.service.create(req).subscribe({next:()=>{this.loading=false;void this.router.navigate(['/admin/drivers']);},error:e=>{this.loading=false;this.error=this.errors.message(e);}});}}
}
